services:
  fastapi:
    container_name: fastapi-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    networks:
      - app-network
    volumes:
      - ./backend/src:/app/src
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  react:
    container_name: react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - fastapi
    command: ["npm", "run", "dev"]

networks:
  app-network:
