version: '3'

services:
  app1:
    build:
      context: my-app
      dockerfile: Dockerfile
    environment:
      APP_NAME: App1

  app2:
    build:
      context: my-app
      dockerfile: Dockerfile
    environment:
      APP_NAME: App2

  app3:
    build:
      context: my-app
      dockerfile: Dockerfile
    environment:
      APP_NAME: App3

  nginx-server:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2
      - app3