services:
  mongo:
    image: mongo:8.0.3-noble
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  node-app:
    # image: node:22.11.0-slim
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - /usr/src/app/node_modules
      - ./app:/usr/src/app
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}

volumes:
  mongo-data:

networks:
  app-network:
